apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-xigjerqb
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-xigjerqb:c878c9ce112a9911601abb923d41b80bfe4741df@sha256:05d52f0f05edcf7a3dc9b1ca1f061ce32c0ffe63f5f866ff3cf6349754ff0281
          name: container-image
